version: 2

builds:
  - id: maggus
    binary: maggus
    ldflags:
      - -s -w
      - -X github.com/dirnei/maggus/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  mode: keep-existing

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
